name: Append to pyproject.toml

on:
  push:
    branches:
      - main  # Or the branch you want to trigger this action

jobs:
  append_file:
    runs-on: ubuntu-latest  # You can use a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Append to pyproject.toml
      run: |
        echo '[tool.poetry]' >> pyproject.toml
        echo 'name = "Testing-project"' >> pyproject.toml
        echo 'version = "0.4.0"' >> pyproject.toml
        echo 'description = "A short description of the project"' >> pyproject.toml
        echo 'authors = ["salman <salmankarim64@gmail.com>"]' >> pyproject.toml

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add pyproject.toml
        git commit -m 'Append to pyproject.toml'
        git push
