name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x" # Adjust according to your needs

      - name: Install Git
        run: sudo apt-get install git

      - name: Create a new tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)

          # Create a tag
          TAG_NAME="v$(date +'%Y.%m.%d')-${COMMIT_HASH:0:7}"
          git tag -a $TAG_NAME -m "Release version $TAG_NAME"

          # Push the tag
          git push origin $TAG_NAME

          # Create a release using the GitHub CLI
          gh release create $TAG_NAME --title "Release $TAG_NAME" --notes "Release notes for $TAG_NAME" --target $COMMIT_HASH
