name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create a new tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)
          
          # Create a tag
          TAG_NAME="v$(date +'%Y.%m.%d')-${COMMIT_HASH:0:7}"
          echo "Tag Name: $TAG_NAME"  # Debugging line to check the tag name
          git tag -a "$TAG_NAME" -m "Release version $TAG_NAME"
          
          # Push the tag
          git push origin "$TAG_NAME"

          # Install GitHub CLI if not available
          if ! command -v gh &> /dev/null; then
            sudo apt-get install gh
          fi
          
          # Create a release using the GitHub CLI
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Release notes for $TAG_NAME" --target "$COMMIT_HASH"
